// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortFolioAPI.DataAccess;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260919171402_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Model.BrevoMailLogs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("destinationEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("htmlContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("senderEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("textContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("brevo_mail_logs");
                });

            modelBuilder.Entity("DataAccess.Model.Viewer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("browser")
                        .HasColumnType("text");

                    b.Property<string>("city")
                        .HasColumnType("text");

                    b.Property<string>("country_code")
                        .HasColumnType("text");

                    b.Property<string>("country_name")
                        .HasColumnType("text");

                    b.Property<string>("device_type")
                        .HasColumnType("text");

                    b.Property<string>("operating_system")
                        .HasColumnType("text");

                    b.Property<string>("page_url")
                        .HasColumnType("text");

                    b.Property<string>("referrer")
                        .HasColumnType("text");

                    b.Property<string>("timezone")
                        .HasColumnType("text");

                    b.Property<string>("user_agent")
                        .HasColumnType("text");

                    b.Property<DateTime>("visit_time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("viewers_list");
                });
#pragma warning restore 612, 618
        }
    }
}
