FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base

WORKDIR /app
EXPOSE 8080

ENV ASPNETCORE_URLS=http://0.0.0.0:8080
ENV ASPNETCORE_ENVIRONMENT=Production


FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

# Copy project files first
COPY PortFolioAPI/PortFolioAPI.csproj PortFolioAPI/
COPY DataAccess/DataAccess.csproj DataAccess/

# Restore
RUN dotnet restore PortFolioAPI/PortFolioAPI.csproj


# Copy the complete source
COPY PortFolioAPI/ PortFolioAPI/
COPY DataAccess/ DataAccess/

# Build
WORKDIR /src/PortFolioAPI

RUN dotnet build PortFolioAPI.csproj \
    -c Release \
    --no-restore \
    -o /app/build


FROM build AS publish

RUN dotnet publish PortFolioAPI.csproj \
    -c Release \
    --no-restore \
    -o /app/publish \
    /p:UseAppHost=false


FROM base AS final

WORKDIR /app

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "PortFolioAPI.dll"]